version: "3.9"
services:
  hummingbot:
    container_name: $(instance_name)
    image: hummingbot/hummingbot:$(tag)
    volumes:
      - "./$(instance_name)/conf:/home/hummingbot/conf"
      - "./$(instance_name)/conf/connectors:/home/hummingbot/conf/connectors"
      - "./$(instance_name)/conf/strategies:/home/hummingbot/conf/strategies"
      - "./$(instance_name)/logs:/home/hummingbot/logs"
      - "./$(instance_name)/data:/home/hummingbot/data"
      - "./$(instance_name)/scripts:/home/hummingbot/scripts"
      - "./$(instance_name)/certs:/home/hummingbot/certs"
    logging:
      driver: "json-file"
      options:
          max-size: "10m"
          max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host